version: "2"
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: go-services
      extra:
        group-params: true
    goimports:
      local-prefixes:
        - go-services
linters:
  enable:
    - exhaustruct_v5
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      verbose: true
    exhaustruct_v5:
      explicit-mode: true
      enforce-patterns:
        - "go-services/.*"
      allow-empty: true
      allow-empty-returns: true
    govet:
      enable-all: true
    ineffassign:
      check-escaping-errors: true
