version: "2"
linters:
  enable:
    - exhaustruct
  settings:
    exhaustruct:
      # List of regular expressions to match type names that should be processed.
      # Anonymous structs can be matched by '<anonymous>' alias.
      #
      # Each regular expression must match the full type name, including package path.
      # For example, to match type `net/http.Cookie` regular expression should be `.*/http\.Cookie`,
      # but not `http\.Cookie`.
      # Default: []
      include:
        - "go-services/.*"
      # allow-empty-returns: true
