inheritedBy:
  files:
    - 'Dockerfile'
  layer: 'application'

tasks:
  docker:
    script: 'IMAGE_NAME="${IMAGE_REGISTRY:+${IMAGE_REGISTRY}/}$project" && docker build -f $projectSource/Dockerfile -t ${IMAGE_NAME}:${GIT_SHA:-latest} -t ${IMAGE_NAME}:latest .'
    options:
      cache: false
      runFromWorkspaceRoot: true
    toolchains: 'system'

  docker-push:
    deps:
      - '~:docker'
    script: 'IMAGE_NAME="${IMAGE_REGISTRY:+${IMAGE_REGISTRY}/}$project" && docker push ${IMAGE_NAME}:${GIT_SHA:-latest} && docker push ${IMAGE_NAME}:latest'
    options:
      cache: false
      runFromWorkspaceRoot: true
    toolchains: 'system'
