inheritedBy:
  language: 'go'

tasks:
  format-go:
    command: 'golangci-lint fmt ./...'
    options:
      cache: false
    toolchains: 'system'

  format:
    deps:
      - '~:format-go'
    options:
      cache: false
