inheritedBy:
  tags:
    and:
      - 'language-go'
      - 'aggregator'

tasks:
  install-go:
    command: 'go mod download'
    options:
      cache: false
    toolchains: 'system'

  install:
    deps:
      - '~:install-go'
