inheritedBy:
  files:
    - 'pom.xml'
  tags:
    and:
      - 'language-java'
    not:
      - 'aggregator'

tasks:
  build-java:
    command: 'mvn -B -ntp clean package -DskipTests'
    deps:
      - target: '^:build-java'
        optional: true
    options:
      cache: true
    toolchains: 'system'

  build:
    deps:
      - '~:build-java'

  test-java:
    command: 'mvn -B -ntp test'
    options:
      cache: true
    toolchains: 'system'

  test:
    deps:
      - '~:test-java'
