// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	uuid "github.com/gofrs/uuid/v5"
)

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Username  string
}
