// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, username, email, first_name, last_name
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, first_name, last_name, email, username
`

type CreateUserParams struct {
	ID        uuid.UUID
	Username  string
	Email     string
	FirstName string
	LastName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users
SET
  username = COALESCE($1, username),
  email = COALESCE($2, email),
  first_name = COALESCE($3, first_name),
  first_name = COALESCE($4, last_name)
WHERE id = $5
`

type UpdateUserParams struct {
	Username  pgtype.Text
	Email     pgtype.Text
	FirstName pgtype.Text
	LastName  pgtype.Text
	ID        uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.ID,
	)
}
